# Generated by Django 2.0.9 on 2019-01-08 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20190108_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='created',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='modified',
        ),
    ]
